# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-09 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badgify', '0003_auto_20180218_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
