# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-15 21:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('badgify', '0004_badgifyuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badgifyuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='badgifyuser',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='BadgifyUser',
        ),
    ]
