# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-09 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badgify', '0004_award_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
