# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-09 21:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('badgify', '0005_badge_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='award',
            name='points',
        ),
    ]
