# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-11 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badgify', '0006_remove_award_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='category',
            field=models.CharField(default='', max_length=255),
        ),
    ]
