timeout: 5600s # One hour
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '--cache-from', 'gcr.io/$PROJECT_ID/web:latest',  # Try to use cached images
    '-t', 'gcr.io/$PROJECT_ID/web:latest',
    '--file=Dockerfile.master',
    '--tag=gcr.io/$PROJECT_ID/web',
    '.' ]
  id: web

images:
- 'gcr.io/$PROJECT_ID/web:latest'