timeout: 5600s # One hour
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-f','./deployment/master/docker/web.Dockerfile',
    '--cache-from', 'gcr.io/$PROJECT_ID/web:latest',
    '-t', 'gcr.io/$PROJECT_ID/web:latest',
    '.' ]
  id: web
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-f','./deployment/master/docker/skyfolk-nginx.Dockerfile',
    '--cache-from', 'gcr.io/$PROJECT_ID/skyfolk-nginx:latest',
    '-t', 'gcr.io/$PROJECT_ID/skyfolk-nginx:latest',
    '.' ]
  id: nginx
  waitFor: ['-'] # runs immediately
- name: 'gcr.io/cloud-builders/kubectl'
  env: ['CLOUDSDK_COMPUTE_ZONE=europe-west3-a', 'CLOUDSDK_CONTAINER_CLUSTER=cluster-1']
  args: ['apply', '-f', '/workspace/deployment/master/k8s']
images:
- 'gcr.io/$PROJECT_ID/web:latest'
- 'gcr.io/$PROJECT_ID/skyfolk-nginx:latest'