timeout: 5600s # One hour
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '--cache-from', 'gcr.io/$PROJECT_ID/web:latest',  # Try to use cached images
    '-t', 'gcr.io/$PROJECT_ID/web:latest',
    '-f','deployment/docker/web.Dockerfile',
    '--tag=gcr.io/$PROJECT_ID/web',
    '.' ]
  id: web
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '--cache-from', 'gcr.io/$PROJECT_ID/skyfolk-nginx:latest',  # Try to use cached images
    '-t', 'gcr.io/$PROJECT_ID/skyfolk-nginx:latest',
    '-f','deployment/docker/skyfolk-nginx.Dockerfile',
    '--tag=gcr.io/$PROJECT_ID/skyfolk-nginx',
    '.' ]
  id: nginx

images:
- 'gcr.io/$PROJECT_ID/web:latest'
- 'gcr.io/$PROJECT_ID/skyfolk-nginx:latest'