timeout: 5600s # One hour
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-f','./deployment/docker/web.Dockerfile',
    '--cache-from', 'gcr.io/$PROJECT_ID/web:latest',
    '-t', 'gcr.io/$PROJECT_ID/web:latest',
    '../../../' ]
  dir: 'deployment/docker'
  id: web
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-f','./deployment/docker/skyfolk-nginx.Dockerfile',
    '--cache-from', 'gcr.io/$PROJECT_ID/skyfolk-nginx:latest',
    '-t', 'gcr.io/$PROJECT_ID/skyfolk-nginx:latest',
    '../../../' ]
    dir: 'deployment/docker'
  id: nginx
images:
- 'gcr.io/$PROJECT_ID/web:latest'
- 'gcr.io/$PROJECT_ID/skyfolk-nginx:latest'