FROM python:3.6

ENV PYTHONUNBUFFERED 1

RUN mkdir /code

WORKDIR /code

ADD requirements/develop.txt /code/

RUN pip install -r develop.txt

RUN apt-get update && apt-get install -y --no-install-recommends apt-utils

# Install PSQL

RUN pip install psycopg2
RUN apt-get update
RUN apt-get install -y postgresql-client

# Install numpy using system package manager
RUN apt-get -y update && apt-get -y install libav-tools imagemagick libopencv-dev python-opencv

# Install some special fonts we use in testing, etc..
RUN apt-get -y install fonts-liberation

RUN apt-get install -y locales && \
    locale-gen C.UTF-8 && \
    /usr/sbin/update-locale LANG=C.UTF-8

RUN apt-get install -y tidy pandoc

ENV LC_ALL C.UTF-8

# do we need all of these, maybe remove some of them?
RUN pip install imageio numpy scipy matplotlib pandas sympy nose decorator tqdm pillow pytest

# install scikit-image after the other deps, it doesn't cause errors this way.
RUN pip install scikit-image sklearn

# install ffmpeg from imageio.
RUN python -c "import imageio; imageio.plugins.ffmpeg.download()"

#add soft link so that ffmpeg can executed (like usual) from command line
RUN ln -s /root/.imageio/ffmpeg/ffmpeg.linux64 /usr/bin/ffmpeg

RUN mkdir -p /var/www/skyfolk.net/run/static/static
RUN mkdir -p /var/www/skyfolk.net/run/static/media

RUN chmod -R g+w /var/www
RUN chmod -R 777 /var/www

RUN chmod -R 770 /root/


# modify ImageMagick policy file so that Textclips work correctly.
RUN cat /etc/ImageMagick-6/policy.xml | sed 's/none/read,write/g'> /etc/ImageMagick-6/policy.xml

VOLUME /root
