version: '3'

services:
  # nginx
  nginx:
    image: nginx:latest
    deploy:
      replicas: 1
    container_name: ng01
    restart: always
    ports:
        - "80:80"
    volumes:
        #- ./deployment/config:/etc/nginx/conf.d
        #- ./skyfolk/static:/static
        - static-content:/var/www/skyfolk.net/run/static/static/
        - static-content:/var/www/skyfolk.net/run/static/media/
    depends_on:
        - web
        - webworker
    networks:
        - skyfolknetwork
    extra_hosts:
        - "cluster:172.17.0.1"

  # redis
  redis:
    image: redis:4.0
    deploy:
      replicas: 1
    hostname: redis
    restart: always
    networks:
      - skyfolknetwork

  # rabbitmq
  rabbit:
    hostname: rabbit
    image: rabbitmq:latest
    deploy:
      replicas: 1
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_ERLANG_COOKIE='secret_cookie'
    ports:
      - "5672:5672"  # we forward this port because it's useful for debugging
      - "15672:15672"  # here, we can access rabbitmq management plugin
    restart: always
    networks:
      - skyfolknetwork

  # django app
  web:
    env_file:
      - web-master-variables.env
    build:
      context: .
      dockerfile: Dockerfile.master
    image: eu.gcr.io/skyfolk-211121/web:latest
    deploy:
      replicas: 1
    hostname: web
    command: ./run_web_master.sh
    volumes:
      #- ./skyfolk/static:/static
      - static-content:/var/www/skyfolk.net/run/static/static/
      - static-content:/var/www/skyfolk.net/run/static/media/
    expose:
        - "8000"
    networks:
      - skyfolknetwork
    depends_on:
      - rabbit
    networks:
      - skyfolknetwork
    restart: always
    extra_hosts:
        - "cluster:172.17.0.1"

  # daphne worker
  webworker:
    image: eu.gcr.io/skyfolk-211121/web:latest
    deploy:
      replicas: 1
    volumes:
      - static-content:/var/www/skyfolk.net/run/static/static/
      - static-content:/var/www/skyfolk.net/run/static/media/
    command: ./run_worker_master.sh
    env_file:
      - web-master-variables.env
    networks:
      - skyfolknetwork
    depends_on:
      - rabbit
    restart: always
    extra_hosts:
        - "cluster:172.17.0.1"

  # celery worker
  celery_worker:
    env_file:
      - web-master-variables.env
    image: eu.gcr.io/skyfolk-211121/web:latest
    deploy:
      replicas: 1
    command: ./run_celery.sh
    volumes:
      - static-content:/var/www/skyfolk.net/run/static/static/
      - static-content:/var/www/skyfolk.net/run/static/media/
    networks:
      - skyfolknetwork
    depends_on:
      - web
    restart: always
    extra_hosts:
        - "cluster:172.17.0.1"

  # celery beat
  celery_beat:
    env_file:
      - web-master-variables.env
    image: eu.gcr.io/skyfolk-211121/web:latest
    deploy:
      replicas: 1
    command: ./run_beat.sh
    volumes:
      - static-content:/var/www/skyfolk.net/run/static/static/
      - static-content:/var/www/skyfolk.net/run/static/media/
    networks:
      - skyfolknetwork
    depends_on:
      - web
    restart: always
    extra_hosts:
        - "cluster:172.17.0.1"

volumes:
  static-content:
networks:
  skyfolknetwork:
    driver: bridge