version: '2'

services:   
  # PostgreSQL database
  db:
    image: postgres:9.6.5
    hostname: db
    environment:
      - POSTGRES_USER=skyfolk_pre
      - POSTGRES_PASSWORD=gDFgg$$G=4h_%H
      - POSTGRES_DB=skyfolk_pre_db
    ports:
      - "5432:5432"
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    restart: always

  # Neo4j datbase
  neo4j:
    image: neo4j:latest
    environment:
      - NEO4J_AUTH=neo4j/1518
      - NEO4J_HEAP_MEMORY=2048
      - NEO4J_CACHE_MEMORY=1G 
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - "./db/dbms:/var/lib/neo4j/data"
    restart: always

  # Redis
  redis:
    image: redis:4.0
    hostname: redis
    restart: always
    
  # elasticsearch
  elasticsearch:
    image: elasticsearch:2.4.2
    ports:
      - "9200:9200"
    volumes:
      - ./esdata/:/usr/share/elasticsearch/data/
    restart: always

  kibana:
    image: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    restart: always

  # RabbitMQ
  rabbit:
    hostname: rabbit
    image: rabbitmq:3.6.12
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_ERLANG_COOKIE='secret_cookie' 
    ports:
      - "5672:5672"  # we forward this port because it's useful for debugging
      - "15672:15672"  # here, we can access rabbitmq management plugin
    restart: always

  # Django web server
  web:
    env_file:
      - web-variables.env
    build:
      context: .
      dockerfile: Dockerfile
    hostname: web
    command: ./run_web.sh
    tmpfs:
      - /tmp
    volumes:
      - .:/code  # mount current directory inside container
    ports:
      - "8000:8000"
    links:
      - db
      - rabbit
      - neo4j
      - redis
      - elasticsearch
    depends_on:
      - db
      - neo4j
      - rabbit
    restart: always
  # Celery worker
  worker:
    env_file:
      - web-variables.env
    build:
      context: .
      dockerfile: Dockerfile
    command: ./run_celery.sh
    tmpfs:
      - /tmp
    volumes:
      - .:/code
    links:
      - neo4j
      - db
      - rabbit
      - redis
      - web
    depends_on:
      - web
    restart: always

volumes:
  dbdata:
    driver: local
