apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f deployment/master/docker-compose.yml -o deployment/master/k8s/
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: nginx
    spec:
      containers:
      - image: gcr.io/skyfolk-211121/skyfolk-nginx:latest
        name: ng01
        ports:
        - containerPort: 80
        resources: {}
        volumeMounts:
        - mountPath: /var/www/skyfolk.net/run/static/static/
          name: static-content
        - mountPath: /var/www/skyfolk.net/run/static/media/
          name: static-content-media
      restartPolicy: Always
      volumes:
      - name: static-content
        persistentVolumeClaim:
          claimName: static-content
      - name: static-content-media
        persistentVolumeClaim:
          claimName: static-content-media
status: {}
