# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-24 18:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Digest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=600)),
                ('link', models.URLField()),
                ('duration', models.CharField(max_length=1)),
                ('date_end', models.DateField()),
                ('provider', models.CharField(max_length=40)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ServicesActivated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('status', models.BooleanField(default=False)),
                ('auth_required', models.BooleanField(default=True)),
                ('self_hosted', models.BooleanField(default=False)),
                ('description', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Services',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='TriggerService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_triggered', models.DateTimeField(null=True)),
                ('status', models.BooleanField(default=False)),
                ('result', models.CharField(default='', max_length=255)),
                ('date_result', models.DateTimeField(auto_now=True, null=True)),
                ('provider_failed', models.IntegerField(db_index=True, default=0)),
                ('consumer_failed', models.IntegerField(db_index=True, default=0)),
                ('counter_ok', models.IntegerField(default=0)),
                ('counter_ko', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=255)),
                ('username', models.CharField(blank=True, default='', max_length=255, verbose_name='username')),
                ('password', models.CharField(blank=True, default='', max_length=128, verbose_name='password')),
                ('host', models.CharField(blank=True, default='', max_length=255, verbose_name='host')),
                ('client_id', models.CharField(blank=True, default='', max_length=255, verbose_name='client id')),
                ('client_secret', models.CharField(blank=True, default='', max_length=255, verbose_name='client secret')),
                ('duration', models.CharField(choices=[('d', 'Day'), ('w', 'Week'), ('m', 'Month'), ('n', 'None')], default='n', max_length=1)),
                ('counter_ok', models.IntegerField(default=0)),
                ('counter_ko', models.IntegerField(default=0)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dash_services.ServicesActivated', to_field='name')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='triggerservice',
            name='consumer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dash_services.UserService'),
        ),
        migrations.AddField(
            model_name='triggerservice',
            name='provider',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dash_services.UserService'),
        ),
        migrations.AddField(
            model_name='triggerservice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
