# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-30 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash_services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userservice',
            name='host',
            field=models.URLField(blank=True, default='', verbose_name='host'),
        ),
    ]
