# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-03 19:07
from __future__ import unicode_literals

import dash_services.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash_services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesactivated',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=dash_services.models.upload_service_thumbnail),
        ),
    ]
