# Generated by Django 2.1.1 on 2018-09-18 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html', models.TextField()),
                ('guide_type', models.CharField(choices=[('WINDOW', 'Window')], default='WINDOW', max_length=16)),
                ('guide_name', models.CharField(max_length=64, unique=True)),
                ('guide_tag', models.TextField(default='all')),
                ('guide_importance', models.IntegerField(default=0)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GuideInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_finished', models.BooleanField(default=False)),
                ('finished_time', models.DateTimeField(blank=True, null=True)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_guide.Guide')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-guide__guide_importance', 'guide__creation_time'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='guideinfo',
            unique_together={('user', 'guide')},
        ),
    ]
