# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insertion_date', models.DateTimeField(auto_now_add=True)),
                ('verb', models.CharField(max_length=255, null=True)),
                ('type', models.CharField(choices=[('publication', 'publication'), ('new_relation', 'new_relation')], default='publication', max_length=20)),
            ],
            options={
                'ordering': ('-insertion_date',),
            },
        ),
    ]
