# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 12:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '0001_initial'),
        ('publications', '0002_auto_20170226_1359'),
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeline',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_timeline', to='user_profile.UserProfile'),
        ),
        migrations.AddField(
            model_name='timeline',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_timeline', to='user_profile.UserProfile'),
        ),
        migrations.AddField(
            model_name='timeline',
            name='publication',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='publications.Publication'),
        ),
    ]
