# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtimeline',
            name='content',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
