# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 20:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timeline', '0002_eventtimeline_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtimeline',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_event', to=settings.AUTH_USER_MODEL),
        ),
    ]
