# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 19:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0002_auto_20170308_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtimeline',
            name='publication',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publication', to='publications.Publication'),
        ),
    ]
