# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0003_auto_20170308_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtimeline',
            name='event_type',
            field=models.IntegerField(choices=[(1, 'publication'), (2, 'new_relation'), (3, 'notice'), (4, 'relevant'), (5, 'imagen')], default=1),
        ),
    ]
