# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-30 22:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash_contrib_plugins_poll', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='description',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='title',
        ),
    ]
