# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-31 10:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dash_contrib_plugins_poll', '0002_auto_20180130_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollresponse',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash.DashboardEntry'),
        ),
        migrations.DeleteModel(
            name='Poll',
        ),
    ]
