# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-31 10:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0006_auto_20180125_2325'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dash_contrib_plugins_poll', '0003_auto_20180131_1147'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pollresponse',
            unique_together=set([('user', 'poll')]),
        ),
    ]
