# Generated by Django 2.1.1 on 2018-10-14 11:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('external_services', '0002_userservice_auth_token_secret'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userservice',
            unique_together={('service', 'user')},
        ),
    ]
