REQUEST_FOLLOWING = 1
REQUEST_BLOCKED = 3
REQUEST_STATUSES = ((REQUEST_FOLLOWING, "Following"), (REQUEST_BLOCKED, "Blocked"))
FOLLOWING = 1
BLOCK = 3
RELATIONSHIP_STATUSES = ((FOLLOWING, 1), (BLOCK, 3))
