# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-14 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photologue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='caption',
            field=models.TextField(blank=True, max_length=1000, verbose_name='caption'),
        ),
    ]
