# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-18 13:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_groups', '0001_initial'),
        ('photologue_groups', '0001_initial'),
        ('taggit', '0002_auto_20150616_2121'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photologue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videogroup',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_videos', to='user_groups.UserGroups'),
        ),
        migrations.AddField(
            model_name='videogroup',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_group_videos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='videogroup',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='photogroup',
            name='effect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photogroup_related', to='photologue.PhotoEffect', verbose_name='effect'),
        ),
        migrations.AddField(
            model_name='photogroup',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_photos', to='user_groups.UserGroups'),
        ),
        migrations.AddField(
            model_name='photogroup',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_group_photos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='photogroup',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
