# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-15 18:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photologue', '0002_auto_20170614_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='effect',
        ),
    ]
