# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 12:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers
import user_groups.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('from_like', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_likegroup', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'created',
            },
        ),
        migrations.CreateModel(
            name='RolUserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('A', 'Admin'), ('M', 'Mod'), ('N', 'Normal')], default='A', max_length=1)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rol_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserGroups',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.Group')),
                ('slug', models.SlugField(max_length=256, null=True, unique=True)),
                ('description', models.TextField(blank=True, max_length=1024, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(blank=True, max_length=32, null=True)),
                ('small_image', models.ImageField(blank=True, null=True, upload_to=user_groups.models.upload_small_group_image, verbose_name='small_image')),
                ('large_image', models.ImageField(blank=True, null=True, upload_to=user_groups.models.upload_large_group_image, verbose_name='large_image')),
                ('privacity', models.BooleanField(default=True, help_text='Desactiva esta casilla si quieres que el grupo sea privado.')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_owner', to=settings.AUTH_USER_MODEL)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('users', models.ManyToManyField(blank=True, related_name='users_in_group', to='user_groups.RolUserGroup')),
            ],
            bases=('auth.group',),
        ),
        migrations.AddField(
            model_name='likegroup',
            name='to_like',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_likegroup', to='user_groups.UserGroups'),
        ),
        migrations.AlterUniqueTogether(
            name='likegroup',
            unique_together=set([('from_like', 'to_like')]),
        ),
    ]
