# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-01 09:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0008_alter_user_username_max_length'),
        ('user_groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroups',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.Group')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.SlugField(max_length=500)),
                ('is_public', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_group', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('view_notification', 'View notification'), ('change_description', 'Change description'), ('delete_publication', 'Delete publication'), ('delete_image', 'Delete image'), ('kick_member', 'Kick member'), ('ban_member', 'Ban member'), ('modify_notification', 'Modify notification')),
            },
            bases=('auth.group',),
        ),
    ]
