# Generated by Django 2.1.1 on 2019-03-10 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='likegroup',
            options={},
        ),
    ]
