# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-18 14:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_groups', '0002_usergroups_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroups',
            name='users',
            field=models.ManyToManyField(related_name='user_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
