# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-01 14:46
from __future__ import unicode_literals

from django.db import migrations, models
import user_groups.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_groups', '0003_auto_20170801_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroups',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=user_groups.models.group_avatar_path),
        ),
        migrations.AlterField(
            model_name='usergroups',
            name='back_image',
            field=models.ImageField(blank=True, null=True, upload_to=user_groups.models.group_back_image_path),
        ),
    ]
