# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-11 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_groups', '0003_auto_20180218_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroups',
            name='slug',
            field=models.SlugField(max_length=256, unique=True),
        ),
    ]
