# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-01 16:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_groups', '0004_auto_20170801_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rolusergroup',
            name='user',
        ),
        migrations.DeleteModel(
            name='RolUserGroup',
        ),
    ]
