# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-14 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_groups', '0005_auto_20170801_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroups',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
