# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-18 17:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_groups', '0006_auto_20170814_1253'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usergroups',
            options={'permissions': (('view_notification', 'View notification'), ('can_publish', 'Can publish'), ('change_description', 'Change description'), ('delete_publication', 'Delete publication'), ('delete_image', 'Delete image'), ('kick_member', 'Kick member'), ('ban_member', 'Ban member'), ('modify_notification', 'Modify notification'))},
        ),
    ]
