# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-18 20:20
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0002_auto_20170614_0004'),
        ('user_groups', '0007_auto_20170818_1923'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Following'), (2, 'Follower'), (3, 'Blocked')])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('emitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_group_request', to=settings.AUTH_USER_MODEL)),
                ('notification', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_group_notification', to='notifications.Notification')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_group_request', to='auth.Group')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='requestgroup',
            unique_together=set([('emitter', 'receiver', 'status')]),
        ),
    ]
