# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-16 12:21
from __future__ import unicode_literals

from django.db import migrations, models
import user_groups.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_groups', '0010_grouptheme_hategrouptheme_likegrouptheme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouptheme',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=user_groups.models.group_themes_images),
        ),
    ]
