# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-16 13:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_groups', '0011_auto_20170916_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouptheme',
            name='board_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
    ]
