# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-17 12:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_groups', '0013_auto_20170916_1736'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grouptheme',
            options={'ordering': ('-created',)},
        ),
    ]
