# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-17 12:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_groups', '0014_auto_20170917_1444'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hategrouptheme',
            unique_together=set([('theme', 'by_user')]),
        ),
        migrations.AlterUniqueTogether(
            name='likegrouptheme',
            unique_together=set([('theme', 'by_user')]),
        ),
    ]
