# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 00:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('user_groups', '0015_remove_usergroups_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergroups',
            name='id',
        ),
        migrations.RemoveField(
            model_name='usergroups',
            name='name',
        ),
        migrations.AddField(
            model_name='usergroups',
            name='group_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.Group'),
            preserve_default=False,
        ),
    ]
