# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-17 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_groups', '0015_auto_20170917_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouptheme',
            name='slug',
            field=models.SlugField(default='', unique=True),
            preserve_default=False,
        ),
    ]
