# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 15:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_groups', '0016_grouptheme_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouptheme',
            name='board_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_groups.UserGroups'),
        ),
        migrations.AlterField(
            model_name='likegroup',
            name='to_like',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_likegroup', to='user_groups.UserGroups'),
        ),
        migrations.AlterField(
            model_name='requestgroup',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_group_request', to='user_groups.UserGroups'),
        ),
    ]
