# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-12 15:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_groups', '0017_auto_20171003_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroups',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
