# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-22 21:46
from __future__ import unicode_literals

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('user_groups', '0018_usergroups_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroups',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
