# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-14 15:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dash_services', '0001_initial'),
        ('th_taiga', '0002_auto_20180614_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taiga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=False)),
                ('description', models.CharField(max_length=255)),
                ('project_name', models.CharField(blank=True, max_length=50)),
                ('webhook_secret_key', models.CharField(blank=True, max_length=50, unique=True)),
                ('notify_epic_create', models.BooleanField(default=True)),
                ('notify_epic_change', models.BooleanField(default=True)),
                ('notify_epic_delete', models.BooleanField(default=True)),
                ('notify_relateduserstory_create', models.BooleanField(default=True)),
                ('notify_relateduserstory_delete', models.BooleanField(default=True)),
                ('notify_issue_create', models.BooleanField(default=True)),
                ('notify_issue_change', models.BooleanField(default=True)),
                ('notify_issue_delete', models.BooleanField(default=True)),
                ('notify_userstory_create', models.BooleanField(default=True)),
                ('notify_userstory_change', models.BooleanField(default=True)),
                ('notify_userstory_delete', models.BooleanField(default=True)),
                ('notify_task_create', models.BooleanField(default=True)),
                ('notify_task_change', models.BooleanField(default=True)),
                ('notify_task_delete', models.BooleanField(default=True)),
                ('notify_wikipage_create', models.BooleanField(default=True)),
                ('notify_wikipage_change', models.BooleanField(default=True)),
                ('notify_wikipage_delete', models.BooleanField(default=True)),
                ('trigger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash_services.TriggerService')),
            ],
            options={
                'db_table': 'skyfolk_taiga',
            },
        ),
    ]
