# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 09:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields
import publications.utils
import publications_groups.models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_groups', '0016_grouptheme_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0002_auto_20150616_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraGroupContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=64)),
                ('description', models.CharField(default='', max_length=256)),
                ('image', models.URLField(blank=True, null=True)),
                ('url', models.URLField()),
                ('video', embed_video.fields.EmbedVideoField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PublicationGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=500, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('board_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_groups.UserGroups')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply_group', to='publications_groups.PublicationGroup')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('user_give_me_hate', models.ManyToManyField(blank=True, related_name='hates_group_publication', to=settings.AUTH_USER_MODEL)),
                ('user_give_me_like', models.ManyToManyField(blank=True, related_name='likes_group_publication', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PublicationGroupImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=publications_groups.models.upload_image_group_publication)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='publications_groups.PublicationGroup')),
            ],
        ),
        migrations.CreateModel(
            name='PublicationGroupVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to=publications_groups.models.upload_video_group_publication, validators=[publications.utils.validate_video])),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='publications_groups.PublicationGroup')),
            ],
        ),
        migrations.AddField(
            model_name='extragroupcontent',
            name='publication',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='group_extra_content', to='publications_groups.PublicationGroup'),
        ),
        migrations.AlterUniqueTogether(
            name='publicationgroup',
            unique_together=set([('board_group', 'id')]),
        ),
    ]
