# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-18 17:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications_groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationgroup',
            name='board_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_groups.UserGroups'),
        ),
    ]
