# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-21 21:01
from __future__ import unicode_literals

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('publications_groups', '0002_auto_20180218_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationgroup',
            name='content',
            field=models.TextField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='publicationgroup',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 2, 21, 21, 1, 15, 283668, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
