# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 18:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('publications_groups', '0002_auto_20170818_1949'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraGroupContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=64)),
                ('description', models.CharField(default='', max_length=256)),
                ('image', models.URLField(blank=True, null=True)),
                ('url', models.URLField()),
                ('video', embed_video.fields.EmbedVideoField(blank=True, null=True)),
                ('publication', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='group_extra_content', to='publications_groups.PublicationGroup')),
            ],
        ),
    ]
