# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-06 12:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications_groups', '0003_auto_20180221_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extragroupcontent',
            name='publication',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extra_content', to='publications_groups.PublicationGroup'),
        ),
    ]
