# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 21:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publications_groups', '0003_extragroupcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationgroup',
            name='user_give_me_hate',
            field=models.ManyToManyField(blank=True, related_name='hates_group_publication', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publicationgroup',
            name='user_give_me_like',
            field=models.ManyToManyField(blank=True, related_name='likes_group_publication', to=settings.AUTH_USER_MODEL),
        ),
    ]
