# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-11 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications_groups', '0004_auto_20180706_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationgroup',
            name='content',
            field=models.TextField(max_length=10000),
        ),
    ]
