# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 11:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import publications.utils
import publications_groups.models


class Migration(migrations.Migration):

    dependencies = [
        ('publications_groups', '0004_auto_20170904_2313'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationGroupImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=publications_groups.models.upload_image_group_publication)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='publications_groups.PublicationGroup')),
            ],
        ),
        migrations.CreateModel(
            name='PublicationGroupVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to=publications_groups.models.upload_video_group_publication, validators=[publications.utils.validate_video])),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='publications_groups.PublicationGroup')),
            ],
        ),
    ]
