# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-17 17:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('user_groups', '0015_auto_20170917_1458'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0002_auto_20150616_2121'),
        ('publications_groups', '0005_publicationgroupimage_publicationgroupvideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationTheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=500, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('board_theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_groups.GroupTheme')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply_theme', to='publications_groups.PublicationTheme')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('user_give_me_hate', models.ManyToManyField(blank=True, related_name='hates_theme_publication', to=settings.AUTH_USER_MODEL)),
                ('user_give_me_like', models.ManyToManyField(blank=True, related_name='likes_theme_publication', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='publicationtheme',
            unique_together=set([('board_theme', 'id')]),
        ),
    ]
