# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avatar', '0003_auto_20160712_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatar',
            name='url_image',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
