version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: docker/skyfolk-nginx.Dockerfile
    #image: skyfolk-nginx:1.0.0
    deploy:
      replicas: 1
    container_name: ng01
    restart: always
    ports:
        - "80:80"
    depends_on:
        - web
        - webworker
    networks:
        - skyfolknetwork
    extra_hosts:
        - "cluster:172.17.0.1"
    labels: 
      kompose.service.type: nodeport


  # redis
  redis:
    image: redis:4.0
    deploy:
      replicas: 1
    hostname: redis
    restart: always
    networks:
      - skyfolknetwork

  # rabbitmq
  rabbit:
    hostname: rabbit
    image: rabbitmq:latest
    deploy:
      replicas: 1
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_ERLANG_COOKIE='secret_cookie'
    ports:
      - "5672:5672"  # we forward this port because it's useful for debugging
      - "15672:15672"  # here, we can access rabbitmq management plugin
    restart: always
    networks:
      - skyfolknetwork

  # django app
  web:
    env_file:
      - env/web.env
    build:
      context: .
      dockerfile: docker/web.Dockerfile
    image: skyfolk-web:1.0.0
    deploy:
      replicas: 1
    hostname: web
    command: ./deployment/master/script/run_web.sh
    expose:
        - "8000"
    networks:
      - skyfolknetwork
    depends_on:
      - rabbit
    restart: always
    extra_hosts:
        - "cluster:172.17.0.1"

  # daphne worker
  webworker:
    image: skyfolk-web:1.0.0
    deploy:
      replicas: 1
    command: ./deployment/master/script/run_worker.sh
    env_file:
      - env/web.env
    networks:
      - skyfolknetwork
    depends_on:
      - rabbit
    restart: always
    extra_hosts:
        - "cluster:172.17.0.1"

  # celery worker
  celery_worker:
    env_file:
      - env/web.env
    image: skyfolk-web:1.0.0
    deploy:
      replicas: 1
    command: ./deployment/master/script/run_celery.sh
    networks:
      - skyfolknetwork
    depends_on:
      - web
    restart: always
    extra_hosts:
        - "cluster:172.17.0.1"

  # celery beat
  celery_beat:
    env_file:
      - env/web.env
    image: skyfolk-web:1.0.0
    deploy:
      replicas: 1
    command: ./deployment/master/script/run_beat.sh
    networks:
      - skyfolknetwork
    depends_on:
      - web
    restart: always
    extra_hosts:
        - "cluster:172.17.0.1"

networks:
  skyfolknetwork:
    driver: bridge