timeout: 5600s # One hour
steps:

# Build web image
- name: 'eu.gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-f','./deployment/master/docker/web.Dockerfile',
    '--cache-from', 'eu.gcr.io/$PROJECT_ID/web:latest',
    '-t', 'gcr.io/$PROJECT_ID/web:latest',
    '.' ]
  id: build-web-image
  waitFor: ['-'] # runs immediately

# Push web image
- name: 'eu.gcr.io/cloud-builders/docker'
  args: [
    'push',
    'eu.gcr.io/$PROJECT_ID/web:latest']
  id: push-web-image
  waitFor: ['build-web-image']

# Build nginx image
- name: 'eu.gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-f','./deployment/master/docker/skyfolk-nginx.Dockerfile',
    '--cache-from', 'eu.gcr.io/$PROJECT_ID/skyfolk-nginx:latest',
    '-t', 'gcr.io/$PROJECT_ID/skyfolk-nginx:latest',
    '.' ]
  id: build-nginx-image
  waitFor: ['-']

# Push nginx image
- name: 'eu.gcr.io/cloud-builders/docker'
  args: [
    'push',
    'eu.gcr.io/$PROJECT_ID/web:latest']
  id: push-nginx-image
  waitFor: ['build-nginx-image']

# Update k8s cluster
- name: 'eu.gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', '/workspace/deployment/master/k8s']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=europe-west3-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-1'
  waitFor: ['push-web-image','push-nginx-image']