version: '3'

services:
  # custom nginx
  # TODO: Move to config map when kompose support
  nginx:
    build:
      context: .
      dockerfile: docker/skyfolk-nginx.Dockerfile
    image: gcr.io/skyfolk-211121/skyfolk-nginx:latest
    deploy:
      replicas: 1
    container_name: ng01
    restart: always
    ports:
        - "80:80"
    volumes:
        - static-content:/var/www/skyfolk.net/run/static/static/
        - static-content-media:/var/www/skyfolk.net/run/static/media/
    depends_on:
        - web
        - webworker
    networks:
        - skyfolknetwork
    extra_hosts:
        - "cluster:172.17.0.1"

  # redis
  redis:
    image: redis:4.0
    deploy:
      replicas: 1
    hostname: redis
    restart: always
    networks:
      - skyfolknetwork

  # rabbitmq
  rabbit:
    hostname: rabbit
    image: rabbitmq:latest
    deploy:
      replicas: 1
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_ERLANG_COOKIE='secret_cookie'
    ports:
      - "5672:5672"  # we forward this port because it's useful for debugging
      - "15672:15672"  # here, we can access rabbitmq management plugin
    restart: always
    networks:
      - skyfolknetwork

  # django app
  web:
    env_file:
      - env/web.env
    build:
      context: .
      dockerfile: docker/web.Dockerfile
    image: gcr.io/skyfolk-211121/web:latest
    deploy:
      replicas: 1
    hostname: web
    command: ./deployment/master/script/run_web.sh
    volumes:
      - static-content:/var/www/skyfolk.net/run/static/static/
      - static-content-media:/var/www/skyfolk.net/run/static/media/
    expose:
        - "8000"
    networks:
      - skyfolknetwork
    depends_on:
      - rabbit
    restart: always
    extra_hosts:
        - "cluster:172.17.0.1"

  # daphne worker
  webworker:
    image: gcr.io/skyfolk-211121/web:latest
    deploy:
      replicas: 1
    volumes:
      - static-content:/var/www/skyfolk.net/run/static/static/
      - static-content-media:/var/www/skyfolk.net/run/static/media/
    command: ./deployment/master/script/run_worker.sh
    env_file:
      - env/web.env
    networks:
      - skyfolknetwork
    depends_on:
      - rabbit
    restart: always
    extra_hosts:
        - "cluster:172.17.0.1"

  # celery worker
  celery_worker:
    env_file:
      - env/web.env
    image: gcr.io/skyfolk-211121/web:latest
    deploy:
      replicas: 1
    command: ./deployment/master/script/run_celery.sh
    volumes:
      - static-content:/var/www/skyfolk.net/run/static/static/
      - static-content-media:/var/www/skyfolk.net/run/static/media/
    networks:
      - skyfolknetwork
    depends_on:
      - web
    restart: always
    extra_hosts:
        - "cluster:172.17.0.1"

  # celery beat
  celery_beat:
    env_file:
      - env/web.env
    image: gcr.io/skyfolk-211121/web:latest
    deploy:
      replicas: 1
    command: ./deployment/master/script/run_beat.sh
    volumes:
      - static-content:/var/www/skyfolk.net/run/static/static/
      - static-content-media:/var/www/skyfolk.net/run/static/media/
    networks:
      - skyfolknetwork
    depends_on:
      - web
    restart: always
    extra_hosts:
        - "cluster:172.17.0.1"

volumes:
  static-content:
  static-content-media:
networks:
  skyfolknetwork:
    driver: bridge