apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f deployment/master/docker-compose.yml -o deployment/master/k8s
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: celery-beat
  name: celery-beat
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: celery-beat
    spec:
      containers:
      - args:
        - ./deployment/master/script/run_beat.sh
        env:
        - name: DB_ENV_DB
          valueFrom:
            configMapKeyRef:
              key: DB_ENV_DB
              name: celery-beat-env-web-env
        - name: DB_ENV_POSTGRES_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: DB_ENV_POSTGRES_PASSWORD
              name: celery-beat-env-web-env
        - name: DB_ENV_POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              key: DB_ENV_POSTGRES_USER
              name: celery-beat-env-web-env
        - name: DB_PORT_5432_TCP_ADDR
          valueFrom:
            configMapKeyRef:
              key: DB_PORT_5432_TCP_ADDR
              name: celery-beat-env-web-env
        - name: DB_PORT_5432_TCP_PORT
          valueFrom:
            configMapKeyRef:
              key: DB_PORT_5432_TCP_PORT
              name: celery-beat-env-web-env
        - name: DJANGO_SETTINGS_MODULE
          valueFrom:
            configMapKeyRef:
              key: DJANGO_SETTINGS_MODULE
              name: celery-beat-env-web-env
        - name: EMAIL_HOST
          valueFrom:
            configMapKeyRef:
              key: EMAIL_HOST
              name: celery-beat-env-web-env
        - name: RABBIT_PORT_5672_TCP
          valueFrom:
            configMapKeyRef:
              key: RABBIT_PORT_5672_TCP
              name: celery-beat-env-web-env
        - name: REDIS_PORT_6379_TCP_ADDR
          valueFrom:
            configMapKeyRef:
              key: REDIS_PORT_6379_TCP_ADDR
              name: celery-beat-env-web-env
        - name: SECRET_KEY
          valueFrom:
            configMapKeyRef:
              key: SECRET_KEY
              name: celery-beat-env-web-env
        image: skyfolk-web:1.0.0
        name: celery-beat
        resources: {}
      restartPolicy: Always
status: {}
