apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -v -f docker-compose.yml
    kompose.version: 1.15.0 (e3cd4d4)
  creationTimestamp: null
  labels:
    io.kompose.service: kibana
  name: kibana
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: kibana
    spec:
      containers:
      - image: kibana:4.6.0
        name: kibana
        ports:
        - containerPort: 5601
        resources: {}
        volumeMounts:
        - mountPath: /usr/share/kibana/config
          name: kibana-claim0
      restartPolicy: Always
      volumes:
      - name: kibana-claim0
        persistentVolumeClaim:
          claimName: kibana-claim0
status: {}
