apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -v -f docker-compose.yml
    kompose.version: 1.15.0 (e3cd4d4)
  creationTimestamp: null
  labels:
    io.kompose.service: neo4j
  name: neo4j
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: neo4j
    spec:
      containers:
      - env:
        - name: NEO4J_AUTH
          value: neo4j/1518
        image: neo4j:latest
        name: neo4j
        ports:
        - containerPort: 7474
        - containerPort: 7687
        resources: {}
        volumeMounts:
        - mountPath: /data/dbms
          name: neo4j-claim0
      restartPolicy: Always
      volumes:
      - name: neo4j-claim0
        persistentVolumeClaim:
          claimName: neo4j-claim0
status: {}
