apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -v -f docker-compose.yml
    kompose.version: 1.15.0 (e3cd4d4)
  creationTimestamp: null
  labels:
    io.kompose.service: web
  name: web
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: web
    spec:
      containers:
      - args:
        - ./run_web.sh
        env:
        - name: DB_ENV_DB
          value: skyfolk_db
        - name: DB_ENV_POSTGRES_PASSWORD
          value: skyfolk_password
        - name: DB_ENV_POSTGRES_USER
          value: skyfolk
        - name: DB_PORT_5432_TCP_ADDR
          value: dbpostgres
        - name: DB_PORT_5432_TCP_PORT
          value: "5432"
        - name: DJANGO_SETTINGS_MODULE
          value: skyfolk.settings.develop
        - name: ELASTICSEARCH_URL
          value: elasticsearch
        - name: NEO4J_BOLT_URL
          value: bolt://neo4j:1518@neo4j:7687
        - name: NEO4J_HOST
          value: neo4j
        - name: NEO4J_PASSWORD
          value: "1518"
        - name: NEO4J_USER
          value: neo4j
        - name: RABBIT_PORT_5672_TCP
          value: rabbit
        - name: REDIS_PORT_6379_TCP_ADDR
          value: redis
        image: skyfolk/web
        name: web
        ports:
        - containerPort: 8000
        resources: {}
        volumeMounts:
        - mountPath: /code
          name: web-claim0
        - mountPath: /tmp
          name: web-claim1
      hostname: web
      restartPolicy: Always
      volumes:
      - name: web-claim0
        persistentVolumeClaim:
          claimName: web-claim0
      - name: web-claim1
        persistentVolumeClaim:
          claimName: web-claim1
status: {}
