# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='event_type',
            field=models.IntegerField(choices=[(1, 'publication'), (2, 'new_relation'), (3, 'notice'), (4, 'relevant'), (5, 'imagen')], default=1),
        ),
    ]
