# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-11 18:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extracontent',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publication_extra_content', to='publications.Publication'),
        ),
    ]
