# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 12:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('user_groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationgroup',
            name='board_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_group', to='user_groups.UserGroups'),
        ),
        migrations.AddField(
            model_name='publicationgroup',
            name='g_author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publicationgroup',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply_group', to='publications.PublicationGroup'),
        ),
        migrations.AddField(
            model_name='publicationgroup',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='publicationgroup',
            name='user_give_me_hate',
            field=models.ManyToManyField(blank=True, related_name='hates_group_me', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publicationgroup',
            name='user_give_me_like',
            field=models.ManyToManyField(blank=True, related_name='likes_group_me', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publicationgroup',
            name='user_share_me',
            field=models.ManyToManyField(blank=True, related_name='share_group_me', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publicationdeleted',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publication',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publication',
            name='board_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publication',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='publications.Publication'),
        ),
        migrations.AddField(
            model_name='publication',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='publication',
            name='user_give_me_hate',
            field=models.ManyToManyField(blank=True, related_name='hates_me', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publication',
            name='user_give_me_like',
            field=models.ManyToManyField(blank=True, related_name='likes_me', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publication',
            name='user_share_me',
            field=models.ManyToManyField(blank=True, related_name='share_me', to=settings.AUTH_USER_MODEL),
        ),
    ]
