# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-21 11:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications_gallery', '0002_auto_20170621_1333'),
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='shared_photo_publication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='publications_gallery.PublicationPhoto'),
        ),
    ]
