# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 20:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications_gallery', '0004_auto_20170927_1717'),
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='shared_video_publication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='publications_gallery.PublicationVideo'),
        ),
    ]
