# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-13 13:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import publications.models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_extracontent_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=publications.models.upload_image_publication)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='publications.Publication')),
            ],
        ),
    ]
