# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 22:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_auto_20170308_2317'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publication',
            options={},
        ),
        migrations.AlterModelOptions(
            name='publicationgroup',
            options={},
        ),
        migrations.AlterModelOptions(
            name='publicationphoto',
            options={},
        ),
    ]
