# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_publication_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='hated',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='publication',
            name='liked',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='publication',
            name='shared',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
