# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-14 22:24
from __future__ import unicode_literals

from django.db import migrations, models
import publications.models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_auto_20170411_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=publications.models.upload_image_publication, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='publicationgroup',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=publications.models.upload_image_publication, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='publicationphoto',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=publications.models.upload_image_publication, verbose_name='Image'),
        ),
    ]
