# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-21 11:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications_gallery', '0002_auto_20170621_1333'),
        ('publications', '0002_publication_shared_photo_publication'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='publication',
            unique_together=set([('shared_photo_publication', 'id')]),
        ),
    ]
