# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-15 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_auto_20170415_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extracontent',
            name='description',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='extracontent',
            name='title',
            field=models.CharField(default='', max_length=64),
        ),
    ]
