# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-13 13:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_publicationimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='image',
        ),
        migrations.RemoveField(
            model_name='publicationgroup',
            name='image',
        ),
        migrations.RemoveField(
            model_name='publicationphoto',
            name='image',
        ),
    ]
