# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 17:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publications', '0003_auto_20170327_2221'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedPublication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_by_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='publication',
            name='user_share_me',
            field=models.ManyToManyField(blank=True, related_name='share_me', to='publications.SharedPublication'),
        ),
    ]
