# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-24 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0004_auto_20170624_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='event_type',
            field=models.IntegerField(choices=[(1, 'publication'), (2, 'new_relation'), (3, 'link'), (4, 'relevant'), (5, 'imagen'), (6, 'shared'), (7, 'shared_photo_pub')], default=1),
        ),
    ]
