# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-14 15:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import publications.models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0004_auto_20170613_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to=publications.models.upload_video_publication)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='publications.Publication')),
            ],
        ),
        migrations.RemoveField(
            model_name='publicationdeleted',
            name='image',
        ),
    ]
