# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-11 13:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0004_auto_20170415_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='hated',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='liked',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='shared',
        ),
    ]
