# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 18:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0004_auto_20170328_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='user_share_me',
        ),
        migrations.AddField(
            model_name='publication',
            name='shared_publication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='share_me', to='publications.SharedPublication'),
        ),
        migrations.AddField(
            model_name='sharedpublication',
            name='publication',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='publications.Publication'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='event_type',
            field=models.IntegerField(choices=[(1, 'publication'), (2, 'new_relation'), (3, 'notice'), (4, 'relevant'), (5, 'imagen'), (6, 'shared')], default=1),
        ),
    ]
