# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 18:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publications', '0005_auto_20170328_2011'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sharedpublication',
            unique_together=set([('by_user', 'publication')]),
        ),
    ]
