# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-14 15:43
from __future__ import unicode_literals

from django.db import migrations, models
import publications.models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0005_auto_20170614_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationvideo',
            name='video',
            field=models.FileField(upload_to=publications.models.upload_video_publication, validators=[publications.models.validate_video]),
        ),
    ]
