# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-24 13:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications_gallery', '0002_auto_20170621_1333'),
        ('publications', '0005_auto_20170624_1300'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='publication',
            unique_together=set([('shared_publication', 'id'), ('shared_photo_publication', 'id')]),
        ),
    ]
