# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-24 13:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0006_auto_20170624_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extracontent',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publication_extra_content', to='publications.Publication', unique=True),
        ),
    ]
