# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-11 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0006_auto_20180911_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='edition_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
