# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-09 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0007_auto_20170405_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extracontent',
            name='image',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='publication',
            name='event_type',
            field=models.IntegerField(choices=[(1, 'publication'), (2, 'new_relation'), (3, 'link'), (4, 'relevant'), (5, 'imagen'), (6, 'shared')], default=1),
        ),
    ]
