# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-24 13:38
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0008_auto_20170624_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='extra_content',
        ),
        migrations.AlterField(
            model_name='extracontent',
            name='publication',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extra_content', to='publications.Publication'),
        ),
    ]
