# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-16 15:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publications_gallery', '0007_auto_20170626_1910'),
        ('publications', '0009_auto_20170624_1538'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='publication',
            unique_together=set([('shared_publication', 'id'), ('board_owner', 'id'), ('shared_photo_publication', 'id')]),
        ),
    ]
