# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-19 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0010_auto_20170716_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationdeleted',
            name='type_publication',
            field=models.IntegerField(choices=[(1, 'skyline'), (2, 'foto')], default=1),
        ),
    ]
