# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-14 12:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0011_publicationdeleted_type_publication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicationgroup',
            name='board_group',
        ),
        migrations.RemoveField(
            model_name='publicationgroup',
            name='g_author',
        ),
        migrations.RemoveField(
            model_name='publicationgroup',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='publicationgroup',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='publicationgroup',
            name='user_give_me_hate',
        ),
        migrations.RemoveField(
            model_name='publicationgroup',
            name='user_give_me_like',
        ),
        migrations.RemoveField(
            model_name='publicationgroup',
            name='user_share_me',
        ),
        migrations.DeleteModel(
            name='PublicationGroup',
        ),
    ]
