# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 23:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications_groups', '0005_publicationgroupimage_publicationgroupvideo'),
        ('publications', '0012_auto_20170814_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='shared_group_publication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='publications_groups.PublicationGroup'),
        ),
    ]
