# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 20:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publications', '0035_auto_20170209_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationphoto',
            name='user_give_me_hate',
            field=models.ManyToManyField(blank=True, related_name='hate_photo_me', to=settings.AUTH_USER_MODEL),
        ),
    ]
