# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 21:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('publications', '0036_publicationphoto_user_give_me_hate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicationgroup',
            old_name='author',
            new_name='g_author',
        ),
        migrations.RenameField(
            model_name='publicationphoto',
            old_name='author',
            new_name='p_author',
        ),
    ]
