# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0037_auto_20170209_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='content',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='publicationgroup',
            name='content',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='publicationphoto',
            name='content',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
