# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0038_auto_20170220_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='deleted',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='publicationgroup',
            name='deleted',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='publicationphoto',
            name='deleted',
            field=models.BooleanField(default='False'),
        ),
    ]
