# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 22:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0039_auto_20170221_2317'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationDeleted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='publications.Publication')),
            ],
        ),
    ]
