# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 22:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publications', '0040_publicationdeleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicationdeleted',
            name='publication',
        ),
        migrations.AddField(
            model_name='publicationdeleted',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publicationdeleted',
            name='content',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='publicationdeleted',
            name='created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='publicationdeleted',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='publication_deleted_image'),
        ),
        migrations.AddField(
            model_name='publicationdeleted',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
