# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 22:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0041_auto_20170223_2333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicationdeleted',
            name='tags',
        ),
    ]
