# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-21 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationblog',
            name='content',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='publicationblog',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
