# Generated by Django 2.1.1 on 2019-02-05 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationblog',
            name='title',
            field=models.CharField(default='', max_length=128),
        ),
    ]
