# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-28 20:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications_gallery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicationphoto',
            old_name='p_author',
            new_name='author',
        ),
    ]
