# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-21 11:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications_gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sharedpublicationphoto',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='sharedpublicationphoto',
            name='by_user',
        ),
        migrations.RemoveField(
            model_name='sharedpublicationphoto',
            name='publication',
        ),
        migrations.DeleteModel(
            name='SharedPublicationPhoto',
        ),
    ]
