# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-11 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications_gallery', '0002_auto_20180828_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationphoto',
            name='content',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='publicationvideo',
            name='content',
            field=models.TextField(max_length=10000),
        ),
    ]
