# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-24 13:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('publications_gallery', '0002_auto_20170621_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraContentPubPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=64)),
                ('description', models.CharField(default='', max_length=256)),
                ('image', models.URLField(blank=True, null=True)),
                ('url', models.URLField()),
                ('video', embed_video.fields.EmbedVideoField(blank=True, null=True)),
                ('publication', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='publication_photo_extra_content', to='publications_gallery.PublicationPhoto')),
            ],
        ),
    ]
