# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 15:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications_gallery', '0003_auto_20170927_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationvideo',
            name='board_video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_video', to='photologue.Video'),
        ),
    ]
