# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-24 14:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import publications.utils
import publications_gallery.models


class Migration(migrations.Migration):

    dependencies = [
        ('publications_gallery', '0003_extracontentpubphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=publications_gallery.models.upload_image_photo_publication)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='publications_gallery.PublicationPhoto')),
            ],
        ),
        migrations.CreateModel(
            name='PublicationVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to=publications_gallery.models.upload_video_photo_publication, validators=[publications.utils.validate_video])),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='publications_gallery.PublicationPhoto')),
            ],
        ),
    ]
