# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-24 22:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications_gallery', '0004_publicationimage_publicationvideo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PublicationImage',
            new_name='PublicationPhotoImage',
        ),
        migrations.RenameModel(
            old_name='PublicationVideo',
            new_name='PublicationPhotoVideo',
        ),
    ]
