# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-26 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications_gallery', '0005_auto_20170625_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationphoto',
            name='event_type',
            field=models.PositiveIntegerField(choices=[(1, 'publication'), (3, 'link'), (4, 'relevant')], default=1),
        ),
    ]
