# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 14:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications_gallery', '0005_auto_20171003_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicationphoto',
            name='user_share_me',
        ),
        migrations.RemoveField(
            model_name='publicationvideo',
            name='user_share_me',
        ),
    ]
