# Generated by Django 2.1.1 on 2018-09-30 21:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='authdevices',
            unique_together={('user_profile', 'browser_token')},
        ),
    ]
