# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-21 10:48
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='relationships',
            field=models.ManyToManyField(related_name='profile_relationships', through='user_profile.RelationShipProfile', to='user_profile.Profile'),
        ),
        migrations.AddField(
            model_name='blockedprofile',
            name='from_blocked',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_blocked', to='user_profile.Profile'),
        ),
        migrations.AddField(
            model_name='blockedprofile',
            name='to_blocked',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_blocked', to='user_profile.Profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='blockeds',
            field=models.ManyToManyField(related_name='profile_blockeds', through='user_profile.BlockedProfile', to='user_profile.Profile'),
        ),
        migrations.AlterUniqueTogether(
            name='blockedprofile',
            unique_together=set([('to_blocked', 'from_blocked')]),
        ),
    ]
