# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-11 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='accepted_policy',
            field=models.BooleanField(default=False),
        ),
    ]
