# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-18 09:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_userprofile_is_online'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_online',
        ),
    ]
