# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 11:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_profile', '0002_auto_20170821_1248'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_when_new_notification', models.BooleanField(default=True)),
                ('email_when_recommendations', models.BooleanField(default=True)),
                ('email_when_mp', models.BooleanField(default=True)),
                ('followed_notifications', models.BooleanField(default=True)),
                ('followers_notifications', models.BooleanField(default=True)),
                ('only_confirmed_users', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
