# Generated by Django 2.1.1 on 2019-01-19 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("user_profile", "0002_auto_20180930_2300")]

    operations = [
        migrations.AddField(
            model_name="relationshipprofile",
            name="weight",
            field=models.PositiveIntegerField(default=0),
        )
    ]
