# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-14 14:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_userproxy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProxy',
        ),
    ]
