# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 18:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_notificationsettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-user__date_joined']},
        ),
    ]
