# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-26 13:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_remove_userprofile_is_online'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='tags',
        ),
    ]
