# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-09 22:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_auto_20170926_2039'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='blockedprofile',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='blockedprofile',
            name='from_blocked',
        ),
        migrations.RemoveField(
            model_name='blockedprofile',
            name='to_blocked',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='blockeds',
        ),
        migrations.AlterUniqueTogether(
            name='relationshipprofile',
            unique_together=set([('to_profile', 'from_profile')]),
        ),
        migrations.DeleteModel(
            name='BlockedProfile',
        ),
    ]
