# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-07 18:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_remove_userprofile_tags'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='likeprofile',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='likeprofile',
            name='from_like',
        ),
        migrations.RemoveField(
            model_name='likeprofile',
            name='to_like',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='likeprofiles',
        ),
        migrations.DeleteModel(
            name='LikeProfile',
        ),
    ]
