# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-14 16:59
from __future__ import unicode_literals

from django.db import migrations, models
import user_profile.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='back_image',
            field=models.ImageField(blank=True, null=True, upload_to=user_profile.models.upload_cover_path),
        ),
    ]
