# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-08 11:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_auto_20170607_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='privacity',
        ),
    ]
