# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-10 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_auto_20171109_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationshipprofile',
            name='type',
            field=models.IntegerField(choices=[(1, 1), (3, 3)]),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.IntegerField(choices=[(1, 'Following'), (3, 'Blocked')]),
        ),
    ]
