# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-14 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_profile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_first_login',
            field=models.BooleanField(default=False),
        ),
    ]
