# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-21 21:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_auto_20171110_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_like', to='user_profile.Profile')),
                ('to_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_like', to='user_profile.Profile')),
            ],
        ),
    ]
