# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-08 13:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_remove_userprofile_privacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='emitter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_request', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='request',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_request', to=settings.AUTH_USER_MODEL),
        ),
    ]
