# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-14 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0007_profile_is_first_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_first_login',
            field=models.BooleanField(default=True),
        ),
    ]
