# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-21 21:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0007_likeprofile'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='likeprofile',
            unique_together=set([('to_profile', 'from_profile')]),
        ),
    ]
