# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-18 00:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0008_auto_20171221_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='likeprofile',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
