# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-19 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0008_auto_20170814_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='privacity',
            field=models.CharField(choices=[('OF', 'OnlyFo'), ('OFAF', 'OnlyFAF'), ('A', 'All'), ('N', 'Nothing')], default='A', max_length=4),
        ),
    ]
