# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-08 17:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0008_remove_userprofile_relationships'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='relationship',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='relationship',
            name='from_person',
        ),
        migrations.RemoveField(
            model_name='relationship',
            name='to_person',
        ),
        migrations.DeleteModel(
            name='Relationship',
        ),
    ]
