# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-08 17:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0009_auto_20170608_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_first_login',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='personal_pin',
        ),
    ]
