# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-08 18:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0011_remove_userprofile_requests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='status',
        ),
    ]
