# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-08 19:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0012_remove_userprofile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authdevices',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_to_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
