# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-08 20:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0013_auto_20170608_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affinityuser',
            name='emitter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_profile_affinity', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='affinityuser',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_profile_affinity', to=settings.AUTH_USER_MODEL),
        ),
    ]
