# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-10 19:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0014_auto_20170608_2229'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='affinityuser',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='affinityuser',
            name='emitter',
        ),
        migrations.RemoveField(
            model_name='affinityuser',
            name='receiver',
        ),
        migrations.DeleteModel(
            name='AffinityUser',
        ),
    ]
