# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-04 09:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dashboardentry',
            unique_together=set([('placeholder_uid', 'position')]),
        ),
    ]
