# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 16:06
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0002_auto_20170224_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardsettings',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
