# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-04 09:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0002_auto_20180804_1107'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dashboardentry',
            unique_together=set([('placeholder_uid', 'position', 'workspace')]),
        ),
    ]
