# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-09 23:12
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations

import dash.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0003_auto_20170311_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardworkspace',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', slugify=dash.helpers.slugify_workspace, unique=True, verbose_name='Slug'),
        ),
    ]
