# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 21:05
from __future__ import unicode_literals

import autoslug.fields
import dash.helpers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0003_auto_20170311_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardworkspace',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', slugify=dash.helpers.slugify_workspace, unique=True, verbose_name='Slug'),
        ),
    ]
