# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0003_auto_20170224_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardworkspace',
            name='position',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Position'),
        ),
    ]
