# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-25 22:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0005_auto_20180124_1730'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboardentry',
            options={'permissions': (('copy_entry', 'Copy Entry'),), 'verbose_name': 'Dashboard entry', 'verbose_name_plural': 'Dashboard entries'},
        ),
        migrations.AlterModelOptions(
            name='dashboardworkspace',
            options={'permissions': (('view_workspace', 'View workspace'),), 'verbose_name': 'Dashboard workspace', 'verbose_name_plural': 'Dashboard workspaces'},
        ),
    ]
