# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-14 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photologue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoeffect',
            name='transpose_method',
            field=models.CharField(blank=True, choices=[('FLIP_LEFT_RIGHT', 'Flip left to right'), ('FLIP_TOP_BOTTOM', 'Flip top to bottom'), ('ROTATE_90', 'Rotate 90 degrees counter-clockwise'), ('ROTATE_270', 'Rotate 90 degrees clockwise'), ('ROTATE_180', 'i 180 degrees')], max_length=15, verbose_name='rotate or flip'),
        ),
    ]
