# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-14 22:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photologue', '0002_auto_20170313_2359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='photos',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='sites',
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
