# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-15 18:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photologue', '0003_remove_photo_effect'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='effect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photo_related', to='photologue.PhotoEffect', verbose_name='effect'),
        ),
    ]
