# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-18 21:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import photologue.models
import photologue.validators
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('user_groups', '0008_auto_20170818_2220'),
        ('taggit', '0002_auto_20150616_2121'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photologue', '0004_photo_effect'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to=photologue.models.get_storage_path, validators=[photologue.validators.validate_file_extension], verbose_name='image')),
                ('date_taken', models.DateTimeField(blank=True, help_text='Date image was taken; is obtained from the image EXIF data.', null=True, verbose_name='date taken')),
                ('view_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='view count')),
                ('crop_from', models.CharField(blank=True, choices=[('top', 'Top'), ('right', 'Right'), ('bottom', 'Bottom'), ('left', 'Left'), ('center', 'Center (Default)')], default='center', max_length=10, verbose_name='crop from')),
                ('title', models.CharField(max_length=250, verbose_name='title')),
                ('slug', models.SlugField(help_text='A "slug" is a unique URL-friendly title for an object.', max_length=250, unique=True, verbose_name='slug')),
                ('caption', models.TextField(blank=True, max_length=1000, verbose_name='caption')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date added')),
                ('url_image', models.URLField(blank=True, max_length=255, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=photologue.models.get_storage_path, verbose_name='thumbnail')),
                ('effect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photogroup_related', to='photologue.PhotoEffect', verbose_name='effect')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_photos', to='user_groups.UserGroups')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_group_photos', to=settings.AUTH_USER_MODEL)),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'get_latest_by': 'date_added',
                'verbose_name_plural': 'photos',
                'ordering': ['-date_added'],
                'verbose_name': 'photo',
            },
        ),
    ]
