# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-23 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photologue', '0005_photogroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(max_length=60, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='photogroup',
            name='title',
            field=models.CharField(max_length=60, verbose_name='title'),
        ),
    ]
