# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-24 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photologue', '0006_auto_20170823_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photogroup',
            name='url_image',
            field=models.URLField(default='', max_length=255),
        ),
    ]
