# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 18:39
from __future__ import unicode_literals

from django.db import migrations, models
import photologue.models


class Migration(migrations.Migration):

    dependencies = [
        ('photologue', '0011_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to=photologue.models.upload_thumbnail_video, verbose_name='thumbnail'),
        ),
    ]
