# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-29 09:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photologue', '0012_video_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photogroup',
            name='effect',
        ),
        migrations.RemoveField(
            model_name='photogroup',
            name='group',
        ),
        migrations.RemoveField(
            model_name='photogroup',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='photogroup',
            name='tags',
        ),
        migrations.DeleteModel(
            name='PhotoGroup',
        ),
    ]
