# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photologue', '0017_auto_20170131_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='url_image',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
