# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 01:23
from __future__ import unicode_literals

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('photologue', '0022_auto_20170226_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='thumbnail',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='', verbose_name='thumbnail'),
        ),
    ]
