# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 01:35
from __future__ import unicode_literals

from django.db import migrations, models
import photologue.models


class Migration(migrations.Migration):

    dependencies = [
        ('photologue', '0023_auto_20170226_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=photologue.models.get_storage_path, verbose_name='thumbnail'),
        ),
    ]
