# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-22 21:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skyfolk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Twitter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=False)),
                ('description', models.CharField(max_length=255)),
                ('tag', models.CharField(blank=True, max_length=80, null=True)),
                ('screen', models.CharField(blank=True, max_length=80, null=True)),
                ('fav', models.BooleanField(default=False)),
                ('since_id', models.BigIntegerField(blank=True, null=True)),
                ('max_id', models.BigIntegerField(blank=True, null=True)),
                ('count', models.IntegerField(blank=True, null=True)),
                ('trigger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skyfolk.TriggerService')),
            ],
            options={
                'db_table': 'skyfolk_twitter',
            },
        ),
    ]
