# Generated by Django 2.1.1 on 2019-03-10 11:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0002_auto_20190310_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrank',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='users'),
        ),
    ]
