# Generated by Django 2.1.1 on 2019-03-17 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("awards", "0003_auto_20190310_1254")]

    operations = [
        migrations.AlterUniqueTogether(
            name="userrank", unique_together={("name", "reached_with")}
        )
    ]
